#!/usr/bin/env python

import sys
import os

fn = os.path.dirname(os.path.realpath(__file__)) + '/wake.macs'

macs = {}

with open(fn, 'r') as f:
    for l in f:
        (k,v) = l.split()
        macs[k] = v

def menu(dict):
    arr = []
    for k,v in dict.items():
        arr.append(k)
    for i,k in enumerate(arr):
        print ('%d) %s' % (i+1,k))
    c = input("> ")
    return arr[int(c)-1]

def wake(n):
    import subprocess
    global macs
    subprocess.call(["/usr/bin/wakeonlan",macs[n]])

if len(sys.argv) >= 2:
    wake(sys.argv[1])
else:
    wake(menu(macs))
